# ----------------------------------------------------------
# AI Agent Flow (Manual Trigger)
# ----------------------------------------------------------
#
# This GitHub Actions workflow is triggered manually.
# It orchestrates:
# 1) Checking out the repository code
# 2) Setting up Node.js
# 3) Installing dependencies
# 4) Running the "master-flow.ts" script, which:
#    - Interacts with the Planner Agent to break down the user's request
#    - Loops over each step and calls our "Text-to-Feature" agent to make code changes
#    - Commits changes to a new feature branch
#    - Calls our local AI flow (review/test) to ensure code is valid
# 5) If all steps pass, we do a final test run. Then if everything is good,
#    we open a Pull Request from agent/<feature-name> → main.
# ----------------------------------------------------------

name: AI Agent Flow (Manual)

on:
  workflow_dispatch:
    inputs:
      feature_request:
        description: "Describe the feature or change you want the AI to implement."
        required: true
        type: string

jobs:
  ai-agent:
    runs-on: ubuntu-latest

    # ----------------------------------------------------------
    # We need permissions to write to contents/pull-requests/issues
    # so that we can commit changes and open PRs.
    # ----------------------------------------------------------
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      # --------------------------------------------
      # 1) Check out the repository code
      # --------------------------------------------
      - name: Check out the repository
        uses: actions/checkout@v3

      # --------------------------------------------
      # 2) Set up Node.js environment
      # --------------------------------------------
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # --------------------------------------------
      # 3) Install dependencies
      #    Uses npm ci to do a clean install
      # --------------------------------------------
      - name: Install dependencies
        run: npm ci

      # --------------------------------------------
      # 4) Run the Master Flow script
      #    This script orchestrates the entire
      #    "Plan" → "Implement Steps" → "Review/Test" → "Open PR"
      #    pipeline.
      # --------------------------------------------
      - name: Run AI Master Flow
        run: |
          npx tsx scripts/master-flow.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FEATURE_REQUEST: ${{ github.event.inputs.feature_request }}
          LOCAL_RUN: "1"
